### ISSUE TITLE
RethinkDB Source?

### ISSUE THREAD

**Issue by doodles526** [Clever/optimus#43]
I've been doing some work with RethinkDB, and was wondering if having a RethinkDB source in the core would be useful, or just keep it on my own fork?

**Comment by azylman** [comment]
You shouldn't need to fork optimus to add a RethinkDB source? You can just leave the source in your code without forking optimus. We've done that in several places in our code for one-off source's (e.g. reading from Clever's API)

**Comment by doodles526** [comment]
Good point. Will close
